# Generated by Django 2.2.7 on 2019-11-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoold', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.IntegerField(default=1),
        ),
    ]
