# Generated by Django 2.2.7 on 2019-11-19 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoold', '0003_auto_20191119_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schoold.Age'),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='age',
            name='age',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
