# Generated by Django 2.2.7 on 2019-11-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoold', '0004_auto_20191119_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoold.Age'),
        ),
    ]
