# Generated by Django 2.2.7 on 2019-11-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoold', '0005_auto_20191119_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
