# Generated by Django 2.2.7 on 2019-11-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoold', '0006_trial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoold.Users')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoold.Trial')),
            ],
        ),
    ]
