# Generated by Django 2.2.7 on 2019-11-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoold', '0008_auto_20191120_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoold.Transactions'),
        ),
    ]
