# Generated by Django 2.2.7 on 2019-11-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoold', '0009_auto_20191120_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoold.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoold.Users')),
            ],
        ),
    ]
